# Server name to use
# This can be a group name, or server name
# All punishments imported from "from" will be registered under that server
# Punishments associated with server "global" would be applied to an entire network
# You might want to change this every time you import the punishments to prevent applying punishments to wrong server
server: global

from:
  # hsql or mysql
  type: hsql

  # used if type is hsql
  # path to hsql database file
  location: database.hsql

  # used if type is mysql
  host: localhost
  name: advancedban
  user: advancedban
  password: naetao

to:
  host: localhost
  name: spicyazisaban
  user: spicyazisaban
  password: naetao

# 00000000-0000-0000-0000-000000000000 is an uuid of CONSOLE used internally
fallbackUUID: 00000000-0000-0000-0000-000000000000
